name: Checks

on:
  pull_request:
    paths-ignore:
    - '**/*.md'
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: DeterminateSystems/nix-installer-action@3138316df39ed29be04236d7ffc686fa525866aa # v23
      with:
        summarize: false
    - uses: DeterminateSystems/magic-nix-cache-action@84c0677f58dcedf3b91f8223ce36a9ea5b3c84b7 # v15
      with:
        use-flakehub: false
    - run: nix flake check -L
